FROM node:16.20-bullseye AS build
RUN apt update -qq && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    git curl && npm install -g electron-packager \
    && git clone --depth 1 --branch 2.2.1 https://github.com/BloodHoundAD/BloodHound.git \
    && cd BloodHound && npm install && npm run linuxbuild

FROM debian:11-slim
RUN apt update -qq && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    libasound2 libx11-xcb1 libxss1 libnss3 libxtst6 libgtk-3-0 libglib2.0-0 libgdk-pixbuf2.0-0   \
    && apt clean -y && rm -rf /var/lib/apt/lists/*
COPY --from=build /BloodHound/BloodHound-linux-x64/ /BloodHound
COPY --from=build /BloodHound/Ingestors/ /Ingestors
COPY entrypoint.sh .

ENTRYPOINT ["/entrypoint.sh"]
