FROM ubuntu:20.04

RUN apt update -qq && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    git curl ca-certificates libgtk2.0-0 libx11-xcb1 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 \
    && apt clean -y && rm -rf /var/lib/apt/lists/* \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash \
    && . ~/.nvm/nvm.sh && nvm install v16.20.2 && npm install -g electron-packager

COPY entrypoint.sh .
RUN git clone --depth 1 --branch 1.5.2 https://github.com/BloodHoundAD/BloodHound.git \
    && cd BloodHound && . ~/.nvm/nvm.sh && npm install --legacy-peer-deps && npm run linuxbuild

ENTRYPOINT ["/entrypoint.sh"]
